version: '3'
services:
  backend:
    image: my-app-backend
    build: ./server
    ports:
      - "5001:5000"
    environment:
      - MONGO_URI=mongodb://127.0.0.1:27017/chatApp
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: