services:
  frontend:
    image: my-app-frontend
    build: ./client
    ports:
      - "3001:80"
    depends_on:
      - backend

  backend:
    image: my-app-backend
    build: ./server
    ports:
      - "5003:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatApp
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: