apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-chat-app
  labels:
    app: web-chat-app
spec:
  replicas: 2 # Number of pods to run
  selector:
    matchLabels:
      app: web-chat-app
  template:
    metadata:
      labels:
        app: web-chat-app
    spec:
      containers:
        - name: web-chat-app
          image: web-chat-app:latest # Replace with your Docker image name
          ports:
            - containerPort: 3000 # Port your app listens on
          env:
            - name: NODE_ENV
              value: "production"
---
apiVersion: v1
kind: Service
metadata:
  name: web-chat-service
spec:
  type: NodePort
  selector:
    app: web-chat-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007 # Port exposed on the host
